### ISSUE TITLE
I can not install application

### ISSUE THREAD

**Issue by NuncaLoUsen** [oracle/apex#2]
Hi.

I've downloaded tha application "Customers", but when I try install using the file customers.zip, I see the following error:
Gateway Timeout
The proxy server did not receive a timely response from the upstream server.

Reference #1.872c0ec8.1620992195.1727880b 

I am using the Oracle Apex free hosting at apex.oracle.com.

What's I doing wrong?

Regards,

Jairo

**Comment by Farore9312** [comment]
Hello. I'm also having the same exact issue. I feel like I've tried everything to resolve this with no success.

**Comment by stefandobre** [comment]
There are currently some issues around importing .zip exports on apex.oracle.com
Importing the standard .sql file is the workaround for now.
