### ISSUE TITLE
NOT COMPATIBLE ERROR during import

### ISSUE THREAD

**Issue by miksch27** [oracle/apex#23]
Well,
for some reason, I receive a NOT COMPATIBLE after importing the Oracle owned POLL SAMPLE (marketing, tracking) 
I downloaded the zip from github and imported into a new Oracle APEX workspace via BUILD import... . 
I continue to look around. Nevertheless, if you have any ideas, go ahead and response to me :-)  

![image](https://user-images.githubusercontent.com/27285353/151702578-02c40e55-17a2-4ff7-a0dd-8ac1c5f756c0.png)

Thank you!

**Comment by salomsalim90** [comment]
I have the same problem

**Comment by patrick-wolf** [comment]
Which APEX version do you use? Please verify that you download the POLL starter app from the branch which matches your APEX version. [https://github.com/oracle/apex/tree/21.1/starter-apps/poll](https://github.com/oracle/apex/tree/21.1/starter-apps/poll) and [https://github.com/oracle/apex/tree/21.2/starter-apps/poll](https://github.com/oracle/apex/tree/21.2/starter-apps/poll)

Regards
Patrick

**Comment by vcleks** [comment]
Hi, the solution is to change the branch version to 21.1. as so:
![image](https://user-images.githubusercontent.com/48684633/152781028-5dd1cd9c-ca71-4020-b925-17d770dcfd86.png)
