### ISSUE TITLE
Sample ODATA-Connector - HTTP 400 when using the SAP Websource

### ISSUE THREAD

**Issue by GasparYYC** [oracle/apex#37]
@cczarski-de  reporting this issue as per your comment in today's video to reach out if there are any issues. 

On apex.oracle.com (App: 186919) I created a new page with an IR using the "Sample-SAP-SalesOrder" Web source and the IR reported this:
ORA-20999: REST Data Source returned an HTTP error: HTTP 400: Bad request

I know the websource is working fine, columns were added and outside of APEX data is returned. Exact same issue in our internal 22.1 instance.

When testing the websource "Test Operation" the same error code is shown (See screenshot).

![image](https://user-images.githubusercontent.com/15837880/202525356-40fe4113-4299-4b19-bc02-e5530fff6dd2.png)

Thank you Carsten & APEX team

**Comment by cczarski-de** [comment]
Hi, 
thank you for reporting this. The "Sample-SAP-SalesOrder" REST Source example is not correctly configured in the Sample Applicaion. The "Source supports Total Row Count method" attribute must be set to None, as that REST endpoint does not support result counting.
<img width="911" alt="Bildschirmfoto 2022-11-17 um 19 47 47" src="https://user-images.githubusercontent.com/72857529/202532910-56f4a2d6-13b2-4561-885f-50053709895f.png">

I will update the Sample Application downloadable here; until then, simply navigate to the attributes of your REST Source and set the Source supports Total Row Count method to None. After that, the REST Source should work.

regards
-Carsten

**Comment by cczarski-de** [comment]
I have refreshed the Sample App downloads with that attribute being set correctly.
